export enum TiposEvento {
    DEPOSITO_REALIZADO = "DEPOSITO_REALIZADO",
    RETIRO_REALIZADO = "RETIRO_REALIZADO",
    TRANSFERENCIA_REALIZADA = "TRANSFERENCIA_REALIZADA",
    LOGIN_REALIZADO = "LOGIN_REALIZADO"
}